# This Action builds the example docs in pull requests so that we can view a live preview.
# It uses IBM Cloud to build the Dockerfile at the root of the repository.

name: Preview

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  setup:
    if: |
      (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize') &&
      github.repository_owner == 'Qiskit'
    uses: Qiskit/gh-actions/.github/workflows/code-engine-preview.yml@main
    with:
      code_engine_project: qiskit-sphinx-theme-preview
      docker_image_name: qiskit-sphinx-theme
      docker_image_port: "8000"
    secrets:
      ibmcloud_account: ${{ secrets.IBMCLOUD_ACCOUNT }}
      ibmcloud_api_key: ${{ secrets.IBMCLOUD_API_KEY }}

  teardown:
    if: github.event.action == 'closed' && github.repository_owner == 'Qiskit'
    uses: Qiskit/gh-actions/.github/workflows/code-engine-cleanup.yml@main
    with:
      code_engine_project: qiskit-sphinx-theme-preview
      docker_image_name: qiskit-sphinx-theme
    secrets:
      ibmcloud_account: ${{ secrets.IBMCLOUD_ACCOUNT }}
      ibmcloud_api_key: ${{ secrets.IBMCLOUD_API_KEY }}
